### ISSUE TITLE
Tooltips scroll horizontally when shift is pressed

### ISSUE THREAD

**Issue by mzmonkey** [Sk1erLLC/ScrollableTooltips#4]
You can see it in the attached video

https://user-images.githubusercontent.com/75185931/175777473-cc69f63d-d98a-40de-a51f-f26c66bca70c.mp4

**Comment by Sk1er** [comment]
![image](https://user-images.githubusercontent.com/18709703/175777543-ab545399-ce88-4ad3-8146-b0cfc06a7bcf.jpeg)

**Comment by ghost** [comment]
genuinely not a bug, code responsible is [here](https://github.com/Sk1erLLC/ScrollableTooltips/blob/master/src/main/java/club/sk1er/mods/scrollabletooltips/GuiUtilsOverride.java#L34=)
